install: metadata.json extension.js
	mkdir -p ~/.local/share/gnome-shell/extensions/workspace-isolated-dash/
	cp metadata.json extension.js ~/.local/share/gnome-shell/extensions/workspace-isolated-dash/
