install: metadata.json extension.js
	mkdir -p ~/.local/share/gnome-shell/extensions/activities-debian-logo/
	cp metadata.json extension.js ~/.local/share/gnome-shell/extensions/activities-debian-logo/

uninstall:
	rm -r ~/.local/share/gnome-shell/extensions/activities-debian-logo/
